/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacyjava;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author KhaiTran
 */
public class Agents extends javax.swing.JFrame {

    /**
     * Creates new form Agents
     */
    public Agents() {
        initComponents();
        SelectAg();
    }

Connection Con = null;
Statement St = null;
ResultSet Rs = null;
int work, late;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AgUID = new javax.swing.JTextField();
        AgName = new javax.swing.JTextField();
        AgPhone = new javax.swing.JTextField();
        AgGender = new javax.swing.JComboBox<>();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        ClearBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AgNote = new javax.swing.JTextArea();
        AgAge = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AgPass = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        YesBtn = new javax.swing.JButton();
        NoBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        SellingBtn = new javax.swing.JLabel();
        MedicineBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(4, 127, 49));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 127, 49));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 127, 49));
        jLabel2.setText("UID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 127, 49));
        jLabel3.setText("Họ tên");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(4, 127, 49));
        jLabel7.setText("Password");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(4, 127, 49));
        jLabel9.setText("Giới tính");

        AgUID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AgName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AgPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AgGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam", "Khác" }));
        AgGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgGenderActionPerformed(evt);
            }
        });

        AddBtn.setBackground(new java.awt.Color(4, 127, 49));
        AddBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setLabel("Thêm vào");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(4, 127, 49));
        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Cập nhật");
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(4, 127, 49));
        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Xóa bỏ");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        AgTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UID", "Password", "Họ tên", "Giới tính", "Tuổi", "SĐT", "Số ca làm", "Số ca muộn", "Ghi chú"
            }
        ));
        AgTable.setOpaque(false);
        AgTable.setRowHeight(20);
        AgTable.setSelectionBackground(new java.awt.Color(4, 127, 49));
        AgTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AgTable);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(4, 127, 49));
        jLabel13.setText("Danh sách nhân viên");

        ClearBtn.setBackground(new java.awt.Color(4, 127, 49));
        ClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("Clear");
        ClearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearBtnMouseClicked(evt);
            }
        });
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(4, 127, 49));
        jLabel14.setText("Ghi chú");

        AgNote.setColumns(20);
        AgNote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgNote.setLineWrap(true);
        AgNote.setRows(1);
        AgNote.setWrapStyleWord(true);
        AgNote.setAutoscrolls(false);
        jScrollPane2.setViewportView(AgNote);

        AgAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 127, 49));
        jLabel15.setText("Tuổi");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(4, 127, 49));
        jLabel16.setText("SĐT");

        AgPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgPassActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(4, 127, 49));
        jLabel18.setText("Chấm công:");

        YesBtn.setBackground(new java.awt.Color(204, 51, 0));
        YesBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        YesBtn.setForeground(new java.awt.Color(255, 255, 255));
        YesBtn.setText("Muộn");
        YesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YesBtnMouseClicked(evt);
            }
        });
        YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesBtnActionPerformed(evt);
            }
        });

        NoBtn.setBackground(new java.awt.Color(4, 127, 49));
        NoBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        NoBtn.setForeground(new java.awt.Color(255, 255, 255));
        NoBtn.setText("Không muộn");
        NoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoBtnMouseClicked(evt);
            }
        });
        NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(22, 22, 22)
                .addComponent(NoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesBtn)
                    .addComponent(jLabel18)
                    .addComponent(NoBtn)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AgUID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AgName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AgAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(AgPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UpdateBtn)
                                .addGap(15, 15, 15)
                                .addComponent(DeleteBtn)
                                .addGap(18, 18, 18)
                                .addComponent(ClearBtn)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgGender, 0, 146, Short.MAX_VALUE)
                            .addComponent(AgPass)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(282, 282, 282))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(AgUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AgPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn)
                            .addComponent(UpdateBtn)
                            .addComponent(DeleteBtn)
                            .addComponent(ClearBtn)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NHÂN VIÊN");

        SellingBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SellingBtn.setForeground(new java.awt.Color(0, 204, 102));
        SellingBtn.setText("BÁN HÀNG");
        SellingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellingBtnMouseClicked(evt);
            }
        });

        MedicineBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MedicineBtn.setForeground(new java.awt.Color(0, 204, 102));
        MedicineBtn.setText("THUỐC");
        MedicineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicineBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(SellingBtn)
                    .addComponent(MedicineBtn))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(MedicineBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(SellingBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgGenderActionPerformed

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        if(AgUID.getText().isEmpty() || AgPass.getText().isEmpty() || AgName.getText().isEmpty() || AgAge.getText().isEmpty() || AgPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được bỏ trống thông tin");
        }else{
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "User1", "IoTET103");
                PreparedStatement add = Con.prepareStatement("INSERT INTO AGENTTBL VALUES(?,?,?,?,?,?,?,?,?)");
                add.setString(1, AgUID.getText());
                add.setString(2, AgPass.getText());
                add.setString(3, AgName.getText());
                add.setString(4, AgGender.getSelectedItem().toString());
                add.setInt(5, Integer.valueOf(AgAge.getText()));
                add.setString(6, AgPhone.getText());
                add.setInt(7, 0);
                add.setInt(8, 0);
                add.setString(9, AgNote.getText());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đã thêm vào danh sách");
                Con.close();
                SelectAg();
            } catch (SQLException ex) {
                Logger.getLogger(Agents.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
        if(AgUID.getText().isEmpty() || AgPass.getText().isEmpty() || AgName.getText().isEmpty() || AgAge.getText().isEmpty() || AgPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được bỏ trống thông tin");
        }else{
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "User1", "IoTET103");
                String UpdateQuery = "Update User1.AGENTTBL set PASSWORD = '"+AgPass.getText()+"'"+",HỌTÊN = '"+AgName.getText()+"'"+",TUỔI = "+AgAge.getText()+""+",SĐT = '"+AgPhone.getText()+"'"+",GIỚITÍNH = '"+AgGender.getSelectedItem().toString()+"'"+",GHICHÚ = '"+AgNote.getText()+"'"+"where UID = '" + AgUID.getText()+"'";
                Statement Update = Con.createStatement();
                Update.executeUpdate(UpdateQuery);
                JOptionPane.showMessageDialog(this, "Đã cập nhật thông tin nhân viên");
                SelectAg();
            } catch (SQLException ex) {
                Logger.getLogger(Agents.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_UpdateBtnMouseClicked

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        if(AgUID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhập UID của nhân viên cần xóa");
        }else{
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "User1", "IoTET103");
                String Id = AgUID.getText();
                String Query = "DELETE FROM User1.AGENTTBL WHERE UID = '" + Id +"'";
                Statement Del = Con.createStatement();
                Del.executeUpdate(Query);
                SelectAg();
                JOptionPane.showMessageDialog(this, "Đã xóa khỏi danh sách");
            } catch (SQLException ex) {
                Logger.getLogger(Agents.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void AgTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)AgTable.getModel();
        int MyIndex = AgTable.getSelectedRow();
        AgUID.setText(model.getValueAt(MyIndex, 0).toString());
        AgPass.setText(model.getValueAt(MyIndex, 1).toString());
        AgName.setText(model.getValueAt(MyIndex, 2).toString());
        AgGender.setSelectedItem(model.getValueAt(MyIndex, 3));
        AgAge.setText(model.getValueAt(MyIndex, 4).toString());
        AgPhone.setText(model.getValueAt(MyIndex, 5).toString());
        work = Integer.valueOf(model.getValueAt(MyIndex, 6).toString());
        late = Integer.valueOf(model.getValueAt(MyIndex, 7).toString());
        if(model.getValueAt(MyIndex, 8) == null)
            AgNote.setText("");
        else
            AgNote.setText(model.getValueAt(MyIndex, 8).toString());
    }//GEN-LAST:event_AgTableMouseClicked

    private void ClearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMouseClicked
        AgUID.setText("");
        AgName.setText("");
        AgAge.setText("");
        AgPhone.setText("");
        AgPass.setText("");
        AgNote.setText("");
    }//GEN-LAST:event_ClearBtnMouseClicked

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void AgPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgPassActionPerformed

    private void NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoBtnActionPerformed

    private void NoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBtnMouseClicked
        if(AgUID.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Nhập ID nhân viên");
        else{
            work++;
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "User1", "IoTET103");
                String UpdateQuery = "Update User1.AGENTTBL set SỐCALÀM = "+work+"where UID = '" + AgUID.getText()+"'";
                Statement Update = Con.createStatement();
                Update.executeUpdate(UpdateQuery);
                JOptionPane.showMessageDialog(this, "Đã chấm công");
                SelectAg();
            } catch (SQLException ex) {
                Logger.getLogger(Agents.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_NoBtnMouseClicked

    private void YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesBtnActionPerformed

    private void YesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesBtnMouseClicked
        if(AgUID.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Nhập ID nhân viên");
        else{
            late++;
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "User1", "IoTET103");
                String UpdateQuery = "Update User1.AGENTTBL set SỐCAMUỘN = "+late+"where UID = '" + AgUID.getText()+"'";
                Statement Update = Con.createStatement();
                Update.executeUpdate(UpdateQuery);
                JOptionPane.showMessageDialog(this, "Đã chấm công muộn");
                SelectAg();
            } catch (SQLException ex) {
                Logger.getLogger(Agents.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_YesBtnMouseClicked

    private void MedicineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicineBtnMouseClicked
        new Medicine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicineBtnMouseClicked

    private void SellingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellingBtnMouseClicked
        new Selling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellingBtnMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked
public void SelectAg(){
    try {
        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "User1", "IoTET103");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT * FROM User1.AGENTTBL");
        AgTable.setModel(DbUtils.resultSetToTableModel(Rs));
    } catch (SQLException ex) {
        Logger.getLogger(Agents.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField AgAge;
    private javax.swing.JComboBox<String> AgGender;
    private javax.swing.JTextField AgName;
    private javax.swing.JTextArea AgNote;
    private javax.swing.JTextField AgPass;
    private javax.swing.JTextField AgPhone;
    private javax.swing.JTable AgTable;
    private javax.swing.JTextField AgUID;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel MedicineBtn;
    private javax.swing.JButton NoBtn;
    private javax.swing.JLabel SellingBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton YesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
